<?php
/**
 * Copyright (c) 2021. Udeytech Technologies All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\ObjectManager;

$indexId = $this->getProductId();
$objectManager = ObjectManager::getInstance();
$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
$_product = $objectManager->get('Magento\Catalog\Api\ProductRepositoryInterface')->getById($indexId);
$addToCartUrl = $listBlock->getAddToCartUrl($_product);
?>
<form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post">
    <?php echo $block->getBlockHtml('formkey') ?>
    <div class="makeupconter-product-info" style="display: none;" id="product_addtocart_form_<?php echo $indexId; ?>"
        <?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId(); ?>"/>
            <input type="hidden" name="qty" value="1"/>
        </div>
        <div id="image-loading" style="display: none"></div>
        <div class="product-image">
            <?php $imageUrl = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'product_base_image')->constrainOnly(true)
                ->keepAspectRatio(true)->keepTransparency(true)->keepFrame(false)->resize(220, 220)->getUrl(); ?>
            <img src="<?php echo $imageUrl ?>"/>
        </div>
        <div class="product-info">
            <div class="product-name">
                <h2><?php echo $_product->getName(); ?></h2>
            </div>
            <div class="product-info-wrap">
                <div
                    class="price-box"><?php echo $this->getLayout()->getBlock('product.price.render.default')->render('base_price', $_product); ?></div>
                <div class="product-desc">
                    <p><?php echo $_product->getShortDescription(); ?></p>
                </div>
            </div>
            <div class="product-action">
                <button type="submit" class="add-to-cart"><span><?php echo __('Add to Basket'); ?></span></button>
            </div>
        </div>
    </div>
</form>
