<?php
/**
 * Copyright (c) 2021. Udeytech Technologies All rights reserved.
 * See COPYING.txt for license details.
 */
$kitCollection = $this->getExpertKitCollection();
$_columnCount = $this->getColumnCount();
?>
<ul class="custom-kits-list">
    <?php $i = 0;
    foreach ($kitCollection as $kit): ?>
        <?php $i++; ?>
        <?php
        //.css-line-height-hint
        $title = $kit->getKitChooseTitle();
        $title = explode(" ", $title);
        $title = array_map(/**
         * @param $word
         * @return string
         */ function ($word) {
            return '<span class="word-wrap">'
                . ' <span class="word">' . $word . '</span>'
                . ' <span class="strut"></span>'
                . '</span>';
        }, $title);
        $title = implode("", $title);
        $title = '<span class="css-line-height-hint">'
            . $title
            . '</span>';
        ?>
        <li class="expertkit <?php echo (($i - 1) % $_columnCount == 0) ? 'left' : (($i % $_columnCount == 0) ? 'right' : 'center') ?>"
            id="expertkit_id_<?php echo $kit->getId(); ?>">
            <div><span class="title"><?php echo $title; ?></span></div>
        </li>
    <?php endforeach; ?>
</ul>
