<?php
/**
 * Copyright (c) 2021. Udeytech Technologies All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\ObjectManager;
$_chooseCollection = $this->getExpertKitCollection();
?>
<?php foreach ($_chooseCollection as $_chooseItem): ?>
    <div id="expertkit_description_id_<?php echo $_chooseItem->getId(); ?>" class="expertkit-description"
         style="display: none"><?php echo $_chooseItem->getDescription(); ?></div>
      <ul id="expertkit_products_box_id_<?php echo $_chooseItem->getId(); ?>" class="expertkit-products-box clearfix"
        style="display: none">
           <?php foreach ($_chooseItem->getProducts() as $_product): ?>
            <li class="" id="expert_kit_product_id_<?php echo $_product->getId(); ?>">
                <?php
                $objectManager = ObjectManager::getInstance();
                $productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
                $_productModel = $productCollection->addAttributeToSelect('*')->load($_product->getId());
                ?>
                <?php $_imgSrc = $this->helper('Magento\Catalog\Helper\Image')->init($_productModel, 'small_image')->resize(220) ?>
                <h3 class="product-name"><?php //echo $_helper->productAttribute($_productModel, $_productModel->getName(), 'name') ?></h3>
                <img src="<?php echo $_imgSrc; ?>" width="220" height="220"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_productModel, 'small_image'), null, true) ?>"/>
                <h4 class="product-price"><?php //echo $this->prepareProductKitPrice($_productModel); ?></h4>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endforeach; ?>
