<?php
use Magento\Framework\App\ObjectManager;
/**
 * Copyright (c) 2021. Udeytech Technologies All rights reserved.
 * See COPYING.txt for license details.
 */
$categories = $this->getFreeColorSamplesByCategories();
$config = $this->helper('Udeytech\Totalcustomization\Helper\Data');
?>
<?php foreach ($categories as $currentCategoryId => $category): ?>
    <ul class="quizkit-select-products-box" id="quizkit_select_products_box_id_<?php echo $currentCategoryId; ?>">
        <?php $products = $category['samples']; ?>
        <div id="owl-demo<?php echo $currentCategoryId; ?>" data-mage-init='{
            "OwlCarousel":{
            "autoPlay": 3000,
            "items" : 3,
            "itemsDesktop" : [1199,3],
            "itemsDesktopSmall" : [979,3]
    }
    }
    '>
    <?php foreach ($products as $_product): ?>
        <li class="quizkit-select-product" id="quizkit_select_product_id_<?php echo $_product->getId() ?>">
            <?php $_imgSrc = $config->getProductImageUrl($_product->getId()); ?>
            <h3 class="product-name"><?php $om = ObjectManager::getInstance();
                $pdata = $om->create('Magento\Catalog\Model\Product')->load($_product->getId());
                echo $pdata->getName(); ?></h3>
            <!--            <div class="img" style="background-image: url('')" -->
            <div class="img"><img src="<?php echo $_imgSrc; ?>"></div>
        </li>
    <?php endforeach; ?></div>
    </ul>
    <script>
        require(['jquery'], function ($) {
            $(document).ready(function () {
                $('#quizkit_select_products_box_id_<?php echo $currentCategoryId; ?>').hide();
            });
        });
    </script>
<?php endforeach; ?>
