<?php
/**
 * Copyright (c) 2021. Udeytech Technologies All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\ObjectManager;
$objectManager = ObjectManager::getInstance();
//$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$product = $this->getProduct();
$_associatedProducts = $this->getAssociatedProducts();
//$_associatedProducts = $product->getTypeInstance()->getAssociatedProducts($product);
if ($productImageAttr = $product->getCustomAttribute('udeytech_lookbook_image_night')) {
    $productImageAttr = $product->getCustomAttribute('udeytech_lookbook_image_night');
    $productImage = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'udeytech_lookbook_image_night')->setImageFile($productImageAttr->getValue());
}
?>
<?php if (isset($productImage)) { ?>
    <div id="group-image">
        <img src="<?php echo $productImage->getUrl(); ?>" width="100%"/>
        <?php foreach ($_associatedProducts as $_item): ?>
            <div class="group-plus"
                 id="plus_<?php echo $_item->getId() ?>"
                 data-productid="<?php echo $_item->getId() ?>"
                 style="left:20px;top:20px;"
                 data-pos-x="<?php echo $_item->getPositions()->getPosX(); ?>"
                 data-pos-y="<?php echo $_item->getPositions()->getPosY(); ?>">
            </div>
            <canvas class="group-canvas" id="canvas_<?php echo $_item->getId() ?>"
                    data-product-id="<?php echo $_item->getId() ?>" width="100%"></canvas>
        <?php endforeach; ?>
    </div>
    <div class="group-prod-items-container" width="100%">
        <?php foreach ($_associatedProducts as $_item): ?>
            <div class="group-prod-image" id="image_<?php echo $_item->getId() ?>"
                 data-productid="<?php echo $_item->getId() ?>">
                <?php if ($image = $this->getItemImage($_item)): ?>
                    <div class="img">
                        <img src="<?php echo $image ?>"/>
                    </div>
                <?php endif; ?>
                <div class="desc">
                    <div><strong><?php echo $_item->getName() ?></strong></div>
                    <div><?php echo 'SKU: ' . $_item->getSku() ?></div>
                    <div><?php echo 'Price: ' . $_item->getFinalPrice() ?></div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div style="display:none;">
        <?php foreach ($_associatedProducts as $_item): ?>
            <input data-form-part="product_form" id="positionX_<?php echo $_item->getId() ?>"
                   name="associated_products1[<?php echo $_item->getId() ?>][pos_x]"
                   value="<?php echo $_item->getPositions()->getPosX(); ?>"/>
            <input data-form-part="product_form" name="looktype1" value="night"/>
            <input data-form-part="product_form" id="positionY_<?php echo $_item->getId() ?>"
                   name="associated_products1[<?php echo $_item->getId() ?>][pos_y]"
                   value="<?php echo $_item->getPositions()->getPosY(); ?>"/>
            <input data-form-part="product_form" class="map_input" data-productid="<?php echo $_item->getId() ?>"
                   id="map_<?php echo $_item->getId() ?>"
                   name="associated_products1[<?php echo $_item->getId() ?>][map]"
                   value="<?php echo $_item->getPositions()->getMap(); ?>"/>
        <?php endforeach; ?>
    </div>
<?php } ?>
<script>
    require(['jquery', 'Udeytech_Lookbook/js/custom_product_edit'],
        function ($) {
            $$('.group-plus').each(function (m) {
                m.hide();
            });
            $$('.group-prod-image').each(function (el) {
                el.observe('click', function (k) {
                    canvasInit();
                    $$('.group-prod-image').each(function (m) {
                        m.removeClassName('selected');
                    });
                    $$('.group-plus').each(function (m) {
                        m.hide();
                    });
                    $('#plus_' + $(el).attr('data-productid')).show();
                    $('.group-canvas').hide();
                    $('#canvas_' + $(el).attr('data-productid') + ' canvas').attr('width', $('#group-image').width()).attr('height', $('#group-image').height());
                    $('#canvas_' + $(el).attr('data-productid')).show();
                    el.addClassName('selected');
                    repositionElements();
                });
            });
            $('.group-plus').draggable({
                containment: "#group-image",
                scroll: false,
                stop: function () {
                    tmp_el = $(this);
                    currentY = ($(this).position().top + $(this).height() / 2) / $('#group-image').height();
                    currentX = ($(this).position().left + $(this).width() / 2) / $('#group-image').width();
                    $('#positionX_' + tmp_el.attr('data-productid')).attr('value', currentX);
                    $('#positionY_' + tmp_el.attr('data-productid')).attr('value', currentY);
                    //console.log(currentX+':'+currentY);
                }
            }).addClass('ui-widget-content');
            repositionElements();
            $(window).resize(function () {
                repositionElements();
            });
            $(document).ready(function () {
                //setTimeout( function(){
                // $('#group-image canvas').attr('width', '400').attr('height', '300');
                //$('.canvas-area[data-image-url]').canvasAreaDraw();
                //},1500);
                //convertToPixels();
                $('#group-image canvas').each(function () {
                    id = $(this).attr('data-product-id');
                    $(this).canvasArea({'input_selector': '#map_' + id});
                });
                //var canvasObject = $(".canvas-area[data-image-url]").canvasAreaDraw();
            });

            function convertToPercents() {
                $('.group-canvas').each(function () {
                    id = $(this).attr('data-productid');
                    tmp = $(this).find('input').val();
                    coords_array = tmp.split(',');
                    console.log(coords_array);
                    new_array = [];
                    for (var i = 0; i < coords_array.length; i++) {
                        new_array.push(coords_array[i] / $('#group-image img').width());
                        i++;
                        new_array.push(coords_array[i] / $('#group-image img').height());
                    }
                    //console.log(new_array);
                    $('#map_' + id).val(new_array.join());
                });
            }

            function convertToPixels() {
                $('.map_input').each(function () {
                    id = $(this).attr('data-productid');
                    tmp = $(this).val();
                    percents_array = tmp.split(',');
                    //console.log(percents_array);
                    new_array = [];
                    for (var i = 0; i < percents_array.length; i++) {
                        new_array.push(parseInt(percents_array[i] * $('#group-image img').width()));
                        i++;
                        new_array.push(parseInt(percents_array[i] * $('#group-image img').height()));
                    }
                    //console.log(new_array);
                    $('#canvas_' + id + ' input').attr('value', new_array.join());
                });
            }

            var canvasInitFlag = false;

            function canvasInit() {
                convertToPixels();
                if (!canvasInitFlag) {
                    //$(".canvas-area[data-image-url]").canvasAreaDraw();
                    canvasInitFlag = true;
                }
            }

            function repositionElements() {
                $('.group-plus').each(function () {
                    id = $(this).attr('data-productid');
                    newX = $('#positionX_' + id).attr('value') * $('#group-image').width() - ($(this).width() / 2);
                    newY = $('#positionY_' + id).attr('value') * $('#group-image').height() - ($(this).height() / 2);
                    $(this).css({left: newX + 'px', top: newY + 'px'});
                });
            }

            // return ts;
        }
    );
</script>
