<?php
/**
 * Copyright (c) 2021. Udeytech Technologies All rights reserved.
 * See COPYING.txt for license details.
 */

$_columnCount = 3;
$kit = $this->getProduct();
$items = $this->getBasekitItems();
?>
<ul class="expertkit-items-box" id="expertkit_items_box_id">
    <?php if (isset($items)) : ?>
        <?php $i = 0;
        $k = 0;
        foreach ($items as $key => $_item): ?>
            <?php $i++;
            $k++; ?>
            <li class="expertkit-item <?php echo (($i - 1) % $_columnCount == 0) ? 'left' : (($i % $_columnCount == 0) ? 'right' : 'center') ?>"
                id="expertkit_item_id_<?php echo $key ?>">
                <div class="empty">
                    <?php if ($i == 3) : ?>
                        <span>
                            <?php echo __('Free') ?>
                            <span class="key"><?php echo $k; ?></span>
                            <?php echo __('gift') ?>
                        </span>
                    <?php else: ?>
                        <span>
                            <?php echo __('Select') ?>
                            <span class="key"><?php echo $k; ?></span>
                            <?php echo __('color') ?>
                        </span>
                    <?php endif; ?>

                </div>
                <div class="content" style="display: none">
                    <div class="wrap"></div>
                    <i class="reset-item-button"></i>
                </div>
                <div class="validation-notice" style="display: none">
                    <span>
                        <?php echo __('Select product') ?>
                        <span class="key"><?php echo __('to') ?></span>
                        <?php echo __('complete kit') ?>
                    </span>
                </div>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>
<div data-mage-init='{"basekit": {
       "items": "$(\".expertkit-item\")"
     }
}'>
</div>
